
/*
===========================================================
BUSINESS KPI ANALYSIS
Brazilian E-Commerce (Olist)
===========================================================

Objective:
Analyze key business metrics to understand sales
performance, customer behavior, product performance,
seller performance, payment trends, and delivery efficiency.
===========================================================
*/


/*
===========================================================
               SECTION 1: SALES KPIs
===========================================================
*/


----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the total revenue generated by the business?
----------------------------------------------------------

SELECT
    ROUND(SUM(payment_value), 2) AS total_revenue
FROM payments_cleaned;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many orders have been placed?
----------------------------------------------------------

SELECT
    COUNT(DISTINCT order_id) AS total_orders
FROM orders;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many unique customers have made purchases?
----------------------------------------------------------

SELECT
    COUNT(DISTINCT customer_id) AS total_customers
FROM customers;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many sellers are registered on the platform?
----------------------------------------------------------

SELECT
    COUNT(DISTINCT seller_id) AS total_sellers
FROM sellers;



----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many products are available for sale?
----------------------------------------------------------

SELECT
    COUNT(DISTINCT product_id) AS total_products
FROM products_cleaned;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average value of each order?
----------------------------------------------------------

SELECT
    ROUND(AVG(payment_value), 2) AS average_order_value
FROM payments_cleaned;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the highest payment amount recorded?
----------------------------------------------------------

SELECT
    MAX(payment_value) AS highest_order_value
FROM payments_cleaned;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the lowest payment amount recorded?
----------------------------------------------------------

SELECT
    MIN(payment_value) AS lowest_order_value
FROM payments_cleaned;



----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average delivery time (in days)?
----------------------------------------------------------

SELECT
    ROUND(AVG(DATEDIFF(DAY,
        order_purchase_timestamp,
        order_delivered_customer_date)),2) AS avg_delivery_days
FROM orders
WHERE order_delivered_customer_date IS NOT NULL;


----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average freight cost per order item?
----------------------------------------------------------

SELECT
    ROUND(AVG(freight_value),2) AS average_freight_cost
FROM order_items;

/*
===========================================================
              SECTION 2 : REVENUE ANALYSIS
===========================================================
*/

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How has revenue changed over time?
----------------------------------------------------------

SELECT
    YEAR(o.order_purchase_timestamp) AS order_year,
    MONTH(o.order_purchase_timestamp) AS order_month,
    ROUND(SUM(p.payment_value),2) AS total_revenue
FROM orders o
JOIN payments_cleaned p
    ON o.order_id = p.order_id
GROUP BY
    YEAR(o.order_purchase_timestamp),
    MONTH(o.order_purchase_timestamp)
ORDER BY
    order_year,
    order_month;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many orders were placed each month?
----------------------------------------------------------

SELECT
    YEAR(order_purchase_timestamp) AS order_year,
    MONTH(order_purchase_timestamp) AS order_month,
    COUNT(*) AS total_orders
FROM orders
GROUP BY
    YEAR(order_purchase_timestamp),
    MONTH(order_purchase_timestamp)
ORDER BY
    order_year,
    order_month;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which order statuses generate the highest revenue?
----------------------------------------------------------

SELECT
    o.order_status,
    ROUND(SUM(p.payment_value),2) AS total_revenue
FROM orders o
JOIN payments_cleaned p
ON o.order_id = p.order_id
GROUP BY
    o.order_status
ORDER BY
    total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which individual orders generated the highest revenue?
----------------------------------------------------------

SELECT TOP 10
    order_id,
    ROUND(SUM(payment_value),2) AS total_revenue
FROM payments_cleaned
GROUP BY order_id
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average payment amount by payment type?
----------------------------------------------------------

SELECT
    payment_type,
    ROUND(AVG(payment_value),2) AS average_payment
FROM payments_cleaned
GROUP BY payment_type
ORDER BY average_payment DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which payment methods generate the highest revenue?
----------------------------------------------------------
SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS total_revenue
FROM payments_cleaned
GROUP BY payment_type
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average revenue generated per order?
----------------------------------------------------------
SELECT
    ROUND(
        SUM(payment_value) /
        COUNT(DISTINCT order_id),2
    ) AS average_revenue_per_order
FROM payments_cleaned;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How are orders distributed across different
-- revenue ranges?
----------------------------------------------------------
SELECT
CASE
    WHEN payment_value < 50 THEN 'Below 50'
    WHEN payment_value BETWEEN 50 AND 100 THEN '50 - 100'
    WHEN payment_value BETWEEN 101 AND 250 THEN '101 - 250'
    WHEN payment_value BETWEEN 251 AND 500 THEN '251 - 500'
    ELSE 'Above 500'
END AS revenue_range,

COUNT(*) AS total_orders

FROM payments_cleaned

GROUP BY
CASE
    WHEN payment_value < 50 THEN 'Below 50'
    WHEN payment_value BETWEEN 50 AND 100 THEN '50 - 100'
    WHEN payment_value BETWEEN 101 AND 250 THEN '101 - 250'
    WHEN payment_value BETWEEN 251 AND 500 THEN '251 - 500'
    ELSE 'Above 500'
END

ORDER BY total_orders DESC;

/*
===========================================================
               SECTION 3 : CUSTOMER ANALYSIS
===========================================================
*/

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which states have the highest number of customers?
----------------------------------------------------------

SELECT TOP 10
    customer_state,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which cities have the highest number of customers?
----------------------------------------------------------

SELECT TOP 10
    customer_city,
    COUNT(customer_id) AS total_customers
FROM customers
GROUP BY customer_city
ORDER BY total_customers DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How are customers distributed across states?
----------------------------------------------------------

SELECT
    customer_state,
    COUNT(*) AS total_customers
FROM customers
GROUP BY customer_state
ORDER BY total_customers DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many unique customers exist?
----------------------------------------------------------

SELECT
COUNT(DISTINCT customer_unique_id) AS unique_customers
FROM customers;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which customers placed the highest number of orders?
----------------------------------------------------------

SELECT TOP 10
    c.customer_unique_id,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
ORDER BY total_orders DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many new customers placed their first order each year?
----------------------------------------------------------

WITH First_Order AS
(
    SELECT
        c.customer_unique_id,
        MIN(o.order_purchase_timestamp) AS first_purchase
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
)

SELECT
    YEAR(first_purchase) AS order_year,
    COUNT(customer_unique_id) AS new_customers
FROM First_Order
GROUP BY YEAR(first_purchase)
ORDER BY order_year;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How many new customers joined each month?
----------------------------------------------------------

WITH First_Order AS
(
    SELECT
        c.customer_unique_id,
        MIN(o.order_purchase_timestamp) AS first_purchase
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
)

SELECT
    YEAR(first_purchase) AS order_year,
    MONTH(first_purchase) AS order_month,
    COUNT(customer_unique_id) AS new_customers
FROM First_Order
GROUP BY
    YEAR(first_purchase),
    MONTH(first_purchase)
ORDER BY
    order_year,
    order_month;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which customers have placed more than one order?
----------------------------------------------------------

SELECT
    c.customer_unique_id,
    COUNT(o.order_id) AS total_orders
FROM customers c
JOIN orders o
ON c.customer_id = o.customer_id
GROUP BY c.customer_unique_id
HAVING COUNT(o.order_id) > 1
ORDER BY total_orders DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What percentage of customers are repeat customers?
----------------------------------------------------------

WITH CustomerOrders AS
(
    SELECT
        c.customer_unique_id,
        COUNT(o.order_id) AS total_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    GROUP BY c.customer_unique_id
)

SELECT
ROUND(
100.0 *
COUNT(CASE WHEN total_orders > 1 THEN 1 END)
/
COUNT(*),2
) AS repeat_customer_percentage
FROM CustomerOrders;

/*
===========================================================
               SECTION 4 : PRODUCT ANALYSIS
===========================================================
*/

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which product categories contain the highest number
-- of products?
----------------------------------------------------------

SELECT TOP 10
    product_category_name,
    COUNT(*) AS total_products
FROM products_cleaned
GROUP BY product_category_name
ORDER BY total_products DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which product categories generate the highest revenue?
----------------------------------------------------------

SELECT
    p.product_category_name,
    ROUND(SUM(pay.payment_value),2) AS total_revenue
FROM order_items oi
JOIN products_cleaned p
    ON oi.product_id = p.product_id
JOIN payments_cleaned pay
    ON oi.order_id = pay.order_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which products have been sold the most?
----------------------------------------------------------

SELECT TOP 10
    product_id,
    COUNT(order_id) AS total_sales
FROM order_items
GROUP BY product_id
ORDER BY total_sales DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which individual products generate the highest revenue?
----------------------------------------------------------

SELECT TOP 10
    oi.product_id,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM order_items oi
GROUP BY oi.product_id
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average selling price of products?
----------------------------------------------------------
SELECT
    ROUND(AVG(price),2) AS average_price
FROM order_items;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which products have the highest selling price?
----------------------------------------------------------

SELECT TOP 10
    product_id,
    MAX(price) AS highest_price
FROM order_items
GROUP BY product_id
ORDER BY highest_price DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which products have the lowest selling price?
----------------------------------------------------------

SELECT TOP 10
    product_id,
    MIN(price) AS lowest_price
FROM order_items
GROUP BY product_id
ORDER BY lowest_price ASC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average weight of products?
----------------------------------------------------------

SELECT
    ROUND(AVG(product_weight_g),2) AS average_weight
FROM products_cleaned;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What are the average dimensions of products?
----------------------------------------------------------

SELECT
    ROUND(AVG(product_length_cm),2) AS avg_length,
    ROUND(AVG(product_height_cm),2) AS avg_height,
    ROUND(AVG(product_width_cm),2) AS avg_width
FROM products_cleaned;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average number of photos available
-- for each product?
----------------------------------------------------------

SELECT
    ROUND(AVG(product_photos_qty),2) AS average_photos
FROM products_cleaned;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Are there any product categories without
-- an English translation?
----------------------------------------------------------

SELECT
    p.product_category_name
FROM products_cleaned p
LEFT JOIN category_translation ct
ON p.product_category_name = ct.product_category_name
WHERE ct.product_category_name_english IS NULL;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which product categories have the highest
-- average selling price?
----------------------------------------------------------
SELECT TOP 10
    p.product_category_name,
    ROUND(AVG(oi.price),2) AS average_price
FROM products_cleaned p
JOIN order_items oi
ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY average_price DESC;

/*
===========================================================
               SECTION 5 : SELLER ANALYSIS
===========================================================
*/
SELECT TOP 10
    oi.seller_id,
    ROUND(SUM(oi.price),2) AS total_revenue
FROM order_items oi
GROUP BY oi.seller_id
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which sellers fulfilled the highest number of orders?
----------------------------------------------------------

SELECT TOP 10
    seller_id,
    COUNT(DISTINCT order_id) AS total_orders
FROM order_items
GROUP BY seller_id
ORDER BY total_orders DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which states have the highest number of sellers?
----------------------------------------------------------

SELECT
    seller_state,
    COUNT(*) AS total_sellers
FROM sellers
GROUP BY seller_state
ORDER BY total_sellers DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which cities have the highest number of sellers?
----------------------------------------------------------

SELECT TOP 10
    seller_city,
    COUNT(*) AS total_sellers
FROM sellers
GROUP BY seller_city
ORDER BY total_sellers DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average revenue generated by each seller?
----------------------------------------------------------

SELECT
    ROUND(AVG(seller_revenue),2) AS average_revenue_per_seller
FROM
(
    SELECT
        seller_id,
        SUM(price) AS seller_revenue
    FROM order_items
    GROUP BY seller_id
) AS seller_summary;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Rank sellers based on total revenue generated.
----------------------------------------------------------

SELECT
    seller_id,
    ROUND(SUM(price),2) AS total_revenue,
    RANK() OVER (ORDER BY SUM(price) DESC) AS revenue_rank
FROM order_items
GROUP BY seller_id;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which sellers sold the highest number of products?
----------------------------------------------------------

SELECT TOP 10
    seller_id,
    COUNT(product_id) AS total_products_sold
FROM order_items
GROUP BY seller_id
ORDER BY total_products_sold DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average freight value charged by each seller?
----------------------------------------------------------

SELECT
    seller_id,
    ROUND(AVG(freight_value),2) AS average_freight
FROM order_items
GROUP BY seller_id
ORDER BY average_freight DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which sellers have the highest average product price?
----------------------------------------------------------

SELECT TOP 10
    seller_id,
    ROUND(AVG(price),2) AS average_price
FROM order_items
GROUP BY seller_id
ORDER BY average_price DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Summarize seller performance using total orders,
-- total products sold, and total revenue.
----------------------------------------------------------

SELECT
    seller_id,
    COUNT(DISTINCT order_id) AS total_orders,
    COUNT(product_id) AS total_products_sold,
    ROUND(SUM(price),2) AS total_revenue
FROM order_items
GROUP BY seller_id
ORDER BY total_revenue DESC;

/*
===========================================================
               SECTION 6 : PAYMENT ANALYSIS
===========================================================
*/

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which payment method is used most frequently?
----------------------------------------------------------

SELECT
    payment_type,
    COUNT(*) AS total_transactions
FROM payments_cleaned
GROUP BY payment_type
ORDER BY total_transactions DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which payment method generates the highest revenue?
----------------------------------------------------------

SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS total_revenue
FROM payments_cleaned
GROUP BY payment_type
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average payment value for each payment method?
----------------------------------------------------------

SELECT
    payment_type,
    ROUND(AVG(payment_value),2) AS average_payment
FROM payments_cleaned
GROUP BY payment_type
ORDER BY average_payment DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- How are payments distributed across installment counts?
----------------------------------------------------------

SELECT
    payment_installments,
    COUNT(*) AS total_transactions
FROM payments_cleaned
GROUP BY payment_installments
ORDER BY payment_installments;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What is the average number of installments used
-- for each payment method?
----------------------------------------------------------

SELECT
    payment_type,
    ROUND(AVG(payment_installments),2) AS average_installments
FROM payments_cleaned
GROUP BY payment_type
ORDER BY average_installments DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which payment transactions have the highest values?
----------------------------------------------------------

SELECT TOP 10
    order_id,
    payment_type,
    payment_value
FROM payments_cleaned
ORDER BY payment_value DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- What percentage of total revenue comes from each
-- payment method?
----------------------------------------------------------

SELECT
    payment_type,
    ROUND(SUM(payment_value),2) AS total_revenue,
    ROUND(
        SUM(payment_value) * 100.0 /
        (SELECT SUM(payment_value) FROM payments_cleaned),
        2
    ) AS revenue_percentage
FROM payments_cleaned
GROUP BY payment_type
ORDER BY total_revenue DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which payment method has the highest average payment
-- value per installment?
----------------------------------------------------------

SELECT
    payment_type,
    ROUND(
        AVG(payment_value / NULLIF(payment_installments,0)),
        2
    ) AS average_value_per_installment
FROM payments_cleaned
GROUP BY payment_type
ORDER BY average_value_per_installment DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Which orders were paid using more than one payment
-- method?
----------------------------------------------------------

SELECT
    order_id,
    COUNT(DISTINCT payment_type) AS payment_methods_used
FROM payments_cleaned
GROUP BY order_id
HAVING COUNT(DISTINCT payment_type) > 1
ORDER BY payment_methods_used DESC;

----------------------------------------------------------
-- BUSINESS QUESTION:
-- Summarize payment performance by payment type.
----------------------------------------------------------

SELECT
    payment_type,
    COUNT(*) AS total_transactions,
    ROUND(SUM(payment_value),2) AS total_revenue,
    ROUND(AVG(payment_value),2) AS average_payment
FROM payments_cleaned
GROUP BY payment_type
ORDER BY total_revenue DESC;






